-- Q1.Calculate total revenue generated by each gender

SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM shopping_data
GROUP BY gender;

-- Q2.Find customers who used a discount and spent more than the overall average purchase amount

SELECT
    customer_id,
    gender,
    category,
    purchase_amount,
    discount_applied
FROM shopping_data
WHERE discount_applied = 'Yes'
AND purchase_amount >
(
    SELECT AVG(purchase_amount)
    FROM shopping_data
);

-- Q3.Find the top 5 products with the highest average review rating
SELECT
    item_purchased,
    ROUND(AVG(review_rating),2) AS avg_review_rating
FROM shopping_data
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

-- Q4.Compare average purchase amounts between Standard and Express Shipping
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM shopping_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5.Compare average spending and total revenue between subscribed and non-subscribed customers
SELECT
    subscription_status,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM shopping_data
GROUP BY subscription_status;

-- Q6.Top 5 products with the most discounted purchases
SELECT
    item_purchased,
    COUNT(*) AS discounted_purchases
FROM shopping_data
WHERE discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY discounted_purchases DESC
LIMIT 5;

-- Q7.Segment customers based on previous purchases
SELECT
    customer_id,
    previous_purchases,
    CASE
        WHEN previous_purchases <= 10 THEN 'New Customer'
        WHEN previous_purchases <= 30 THEN 'Returning Customer'
        ELSE 'Loyal Customer'
    END AS customer_segment
FROM shopping_data;

-- Q8.Top 3 most purchased products within each category
SELECT
    category,
    item_purchased,
    total_purchases
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER(
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM shopping_data
    GROUP BY category, item_purchased
) t
WHERE rn <= 3;

-- Q9.Check whether repeat buyers are more likely to subscribe
SELECT
    subscription_status,
    COUNT(*) AS total_customers
FROM shopping_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10.Revenue contribution by age group
SELECT
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        WHEN age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END AS age_group,
    SUM(purchase_amount) AS total_revenue
FROM shopping_data
GROUP BY age_group
ORDER BY total_revenue DESC;